### ISSUE TITLE
Config Per Context

### ISSUE THREAD

**Issue by larntz** [larntz/artui#14]
Depending on the current k8s context use a config specific to that context. 

Config file current looks like: 
```
argocd:
  host: "port-forward"
  namespace: "argocd"
  username: "admin"
  insecure: true # Skip server certificate and domain verification
  grpcweb: false
  plaintext: false # Disable TLS
  port-forward: true # Connect to a random argocd-server port using port forwarding
```

Probably want to do something similar to:
```
argocd:
  default:
    host: "port-forward"
    namespace: "argocd"
    username: "admin"
    insecure: true # Skip server certificate and domain verification
    grpcweb: false
    plaintext: false # Disable TLS
    port-forward: true # Connect to a random argocd-server port using port forwarding
  contexts:
    - name: context1
      host: "port-forward"
      namespace: "argocd"
      username: "admin"
      insecure: true # Skip server certificate and domain verification
      grpcweb: false
      plaintext: false # Disable TLS
      port-forward: true # Connect to a random argocd-server port using port forwarding
    - name: context2
      host: "port-forward"
      namespace: "argocd"
      username: "admin"
      insecure: false # Skip server certificate and domain verification
      grpcweb: false
      plaintext: true # Disable TLS
      port-forward: true # Connect to a random argocd-server port using port forwarding
```
